# Setup
title:               UL
tagline:             'Web Back-end 개발자를 향한 여정'
description:         '블로그 이사 중입니다. <a href="https://stella-ul.tistory.com" target="_blank">이전 블로그</a>'
url:                 'https://ulzcq.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              UL
  url:               https://twitter.com/3_minutes_12
  email:             stellas78@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
